### ISSUE TITLE
sinerider-scoring service stability Issue

### ISSUE THREAD

**Issue by alhardwarehyde** [hackclub/sinerider#531]
### Description

Fix Leaderboard Stability

**Comment by grymmy** [comment]
Specifically this is an issue in sinerider-api with the following errors in the request intercept handler:
```
200 https://sinerider.com/App/Levels/ooo.js
200 https://sinerider.com/App/Levels/convergence.js
200 https://sinerider.com/App/Levels/swamp.js
file:///home/graham/work/sinerider-scoring/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:324
        error: new ProtocolError(),
            ^
ProtocolError: Protocol error (Fetch.fulfillRequest): Invalid header
  at file:///home/graham/work/sinerider-scoring/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:324:24
  at new Promise (<anonymous>)
  at CDPSessionImpl.send (file:///home/graham/work/sinerider-scoring/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:320:16)
  at HTTPRequest._HTTPRequest_respond (file:///home/graham/work/sinerider-scoring/node_modules/puppeteer-core/lib/esm/puppeteer/common/HTTPRequest.js:511:10)
  at HTTPRequest.respond (file:///home/graham/work/sinerider-scoring/node_modules/puppeteer-core/lib/esm/puppeteer/common/HTTPRequest.js:409:100)
  at file:///home/graham/work/sinerider-scoring/build/src/main.js:127:27
  at Generator.next (<anonymous>)
  at file:///home/graham/work/sinerider-scoring/build/src/main.js:7:71
  at new Promise (<anonymous>)
  at __awaiter (file:///home/graham/work/sinerider-scoring/build/src/main.js:3:12)
```

**Comment by grymmy** [comment]
Currently under the belief that this is fixed via https://github.com/JosiasAurel/sinerider-scoring/pull/22.  If I observe this reoccurring I will reopen this issue.
