### ISSUE TITLE
First cutscene doesn't play.

### ISSUE THREAD

**Issue by Captainexpo-1** [hackclub/sinerider#595]
### Description

In the first cutscene it loads, but then the screen is just white.

### Additional information

Error:

Uncaught TypeError: sledders is not iterable
    at Object.refreshTriggered (Goal.js:96:21)
    at Object.tick (Goal.js:78:12)
    at tick (PathGoal.js:225:10)
    at Object.reset (PathGoal.js:381:5)
    at awake (Goal.js:69:10)
    at Object.sendLifecycleEvent (Entity.js:115:35)
    at _.invokeEach (extensions.js:32:30)
    at sendLifecycleEvent (Entity.js:118:7)
    at Object.awake (Entity.js:89:5)
    at tickInternal (main.js:253:9)

**Comment by polytroper** [comment]
Fixed
